- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - networking-nuage-tempest-smoke:
            override-checkout: stable/queens
            required-projects: &required-projects
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
              - name: OpenStack/nuage-openstack-neutronclient
                override-checkout: 5.4/queens
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - networking-nuage-tempest-smoke:
            override-checkout: stable/queens
            required-projects: *required-projects

    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            override-checkout: stable/queens
            required-projects: *required-projects

    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-sriov:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-cli:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-scenario:
            override-checkout: stable/queens
            required-projects: *required-projects
        - tempest-full:
            override-checkout: stable/queens
            required-projects: *required-projects

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-smoke-multiversion-20.10

    periodic-sunday:
      jobs:
        - networking-nuage-tempest-lbaas:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-fwaas-v1:
            override-checkout: stable/queens
            required-projects: *required-projects
        - ovs-restart:
            override-checkout: stable/queens
            required-projects: *required-projects

    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            override-checkout: stable/queens
            required-projects: *required-projects

- job:
    name: networking-nuage-tempest-smoke-multiversion-20.10
    parent: networking-nuage-tempest-smoke
    override-checkout: stable/queens
    vars:
      ci_vsp_name: ci-vsp-multiversion-20.10
    required-projects: *required-projects
