- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - networking-nuage-tempest-smoke:
            override-checkout: stable/rocky
            required-projects: &required-projects
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
              - name: OpenStack/nuage-openstack-neutronclient
                override-checkout: 5.4/rocky
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.9.0

    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - networking-nuage-tempest-smoke:
            override-checkout: stable/rocky
            required-projects: *required-projects

    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            override-checkout: stable/rocky
            required-projects: *required-projects

    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-sriov:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-cli:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-scenario:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - tempest-full:
            override-checkout: stable/rocky
            required-projects: *required-projects

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - ovs-restart:
            override-checkout: stable/rocky
            required-projects: *required-projects

    periodic-sunday:
      jobs:
        - networking-nuage-tempest-lbaas:
            override-checkout: stable/rocky
            required-projects: *required-projects
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            required-projects: *required-projects

    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            required-projects: *required-projects
