- project:
    templates:
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke
    experimental:
      jobs:
        - networking-nuage-vtep-vxlan
    virtio:
      jobs:
        - networking-nuage-tempest-virtio
    sriov:
      jobs:
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-sriov-flat-vlan
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal
    full:
      jobs:
        - networking-nuage-tempest-virtio
        - networking-nuage-tempest-virtio-vsdipam
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-sriov-vsdipam
        - networking-nuage-tempest-sriov-flat-vlan
        - networking-nuage-tempest-baremetal
        - networking-nuage-tempest-baremetal-vsdipam
        - networking-nuage-tempest-scenario
        - networking-nuage-tempest-scenario-vsdipam
        - networking-nuage-vtep-vlan-upstream
        - networking-nuage-vtep-vlan-nuage
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev
        - networking-nuage-tempest-api-virtio-forwarder
    cli:
      jobs:
        - networking-nuage-tempest-cli
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows
    scenario:
      jobs:
        - networking-nuage-tempest-scenario
    scale:
      jobs:
        - networking-nuage-tempest-scale
    upstream:
      jobs:
        - tempest-full
        - tempest-full-vsdipam
    periodic:
      jobs:
        - networking-nuage-tempest-virtio
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-baremetal
        - networking-nuage-tempest-scenario
        - networking-nuage-tempest-cli
        - tempest-full
        - networking-nuage-tempest-api-switchdev
        - networking-nuage-vtep-vlan-upstream
        - networking-nuage-vtep-vlan-nuage
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp
        - networking-nuage-tempest-sriov-flat-vlan
        - networking-nuage-rally-task
        - networking-nuage-vtep-vxlan
        - networking-nuage-tempest-multinode
        - networking-nuage-tempest-nova-evacuate
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows
        - networking-nuage-tempest-scale
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-tempest-virtio-vsdipam
        - networking-nuage-tempest-sriov-vsdipam
        - networking-nuage-tempest-baremetal-vsdipam
        - networking-nuage-tempest-scenario-vsdipam
        - tempest-full-vsdipam
        - ovs-restart

- job:
    name: networking-nuage-rally-task
    parent: rally-task-at-devstack
    branches: ^(?!stable/(newton|ocata|pike)).*$
    nodeset: openstack-single-node
    required-projects:
      - name: opendev.org/openstack/devstack
      - name: opendev.org/openstack/devstack-gate
      - name: opendev.org/openstack/rally
      - name: opendev.org/openstack/rally-openstack
      - name: OpenStack/nuage-openstack-neutron
    pre-run: playbooks/pre-run.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    vars:
      use_pypi: true
      vsp_release: '20.5'
      nuage_fip_range: "172.{{ 255 | random }}.{{ 255 | random }}"
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        nuage-openstack-neutron: https://github.com/nuagenetworks/nuage-openstack-neutron.git
      devstack_services:
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
      devstack_localrc:
        FLOATING_RANGE: "{{ nuage_fip_range }}.0/24"
        PUBLIC_NETWORK_GATEWAY: "{{ nuage_fip_range }}.1"
        Q_PLUGIN: ml2
        Q_USE_PROVIDERNET_FOR_PUBLIC: False
        Q_ML2_PLUGIN_EXT_DRIVERS: nuage_network,nuage_subnet,nuage_port,port_security
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: nuage
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan
        NUAGE_VSD_DEF_NETPART_NAME: "NuageCi-{{ 1000000 | random }}"
        NUAGE_FIP_UNDERLAY: True
        NUAGE_USE_METADATA: True
        NUAGE_METADATA_SHARED_SECRET: sharedsecret
        NUAGE_PAT: legacy_disabled
        OVS_BRIDGE: alubr0
      rally_task: rally-jobs/nuage-openstack-neutron.yaml
    timeout: 7800

- job:
    name: legacy-tempest-aio-base
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      vsp_release: '20.5'
      job_flavor: ml2
      python3: False
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      vsp_release: '20.5'
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest
