- project:
    templates:
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke:
            required-projects: &required-projects-wallaby
              - openstack/neutron
              - name: openstack/neutron-tempest-plugin
                override-checkout: 1.8.0
              - openstack/tempest

    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke:
            required-projects: *required-projects-wallaby
    experimental:
      jobs:
        - networking-nuage-vtep-vxlan:
            required-projects: *required-projects-wallaby
    full:
      jobs:
        - networking-nuage-tempest-virtio:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-virtio-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov-flat-vlan:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-baremetal:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-baremetal-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-scenario:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-scenario-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-vtep-vlan-upstream:
            required-projects: *required-projects-wallaby
        - networking-nuage-vtep-vlan-nuage:
            required-projects: *required-projects-wallaby
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            required-projects: *required-projects-wallaby
    octavia:
      jobs:
        - networking-nuage-octavia:
            required-projects: *required-projects-wallaby
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/wallaby/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            required-projects: *required-projects-wallaby
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/wallaby/amphora-x64-haproxy.qcow2"
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-api-virtio-forwarder:
            required-projects: *required-projects-wallaby
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            required-projects: *required-projects-wallaby
    scale:
      jobs:
        - networking-nuage-tempest-scale:
            required-projects: *required-projects-wallaby
    upstream:
      jobs:
        - tempest-full:
            required-projects: *required-projects-wallaby
        - tempest-full-vsdipam:
            required-projects: *required-projects-wallaby
    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-baremetal:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-scenario:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-cli:
            required-projects: *required-projects-wallaby
        - networking-nuage-vtep-vlan-upstream:
            required-projects: *required-projects-wallaby
        - networking-nuage-vtep-vlan-nuage:
            required-projects: *required-projects-wallaby
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov-flat-vlan:
            required-projects: *required-projects-wallaby
        - networking-nuage-vtep-vxlan:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-multinode:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-nova-evacuate:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-api-switchdev:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-api-virtio-forwarder:
            required-projects: *required-projects-wallaby
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-scale:
            required-projects: *required-projects-wallaby
        - networking-nuage-octavia:
            required-projects: *required-projects-wallaby
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/wallaby/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            required-projects: *required-projects-wallaby
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/wallaby/amphora-x64-haproxy.qcow2"
        - networking-nuage-tempest-virtio-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-sriov-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-baremetal-vsdipam:
            required-projects: *required-projects-wallaby
        - networking-nuage-tempest-scenario-vsdipam:
            required-projects: *required-projects-wallaby
        - tempest-full-vsdipam:
            required-projects: *required-projects-wallaby
        - ovs-restart:
            required-projects: *required-projects-wallaby
