- project:
    templates:
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke
    experimental:
      jobs:
        - networking-nuage-vtep-vxlan
    virtio:
      jobs:
        - networking-nuage-tempest-virtio
    sriov:
      jobs:
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-sriov-flat-vlan
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal
    full:
      jobs:
        - networking-nuage-tempest-virtio
        - networking-nuage-tempest-virtio-vsdipam
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-sriov-vsdipam
        - networking-nuage-tempest-sriov-flat-vlan
        - networking-nuage-tempest-baremetal
        - networking-nuage-tempest-baremetal-vsdipam
        - networking-nuage-tempest-scenario
        - networking-nuage-tempest-scenario-vsdipam
        - networking-nuage-vtep-vlan-upstream
        - networking-nuage-vtep-vlan-nuage
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp
    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            required-projects:
              - OpenStack/neutron-fwaas
            vars:
              devstack_plugins:
                neutron-fwaas: https://github.mv.usa.alcatel.com/OpenStack/neutron-fwaas.git
              devstack_localrc:
                USE_PYTHON3: true
                FORCE_CONFIG_DRIVE: true
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev
        - networking-nuage-tempest-api-virtio-forwarder
    cli:
      jobs:
        - networking-nuage-tempest-cli
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows
    scenario:
      jobs:
        - networking-nuage-tempest-scenario
    scale:
      jobs:
        - networking-nuage-tempest-scale
    upstream:
      jobs:
        - tempest-full
        - tempest-full-vsdipam
    periodic:
      jobs:
        - networking-nuage-tempest-virtio
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-baremetal
        - networking-nuage-tempest-scenario
        - networking-nuage-tempest-cli
        - tempest-full
        - networking-nuage-vtep-vlan-upstream
        - networking-nuage-vtep-vlan-nuage
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp
        - networking-nuage-tempest-sriov-flat-vlan
        - networking-nuage-vtep-vxlan
        - networking-nuage-tempest-multinode
        - networking-nuage-tempest-nova-evacuate
        - networking-nuage-tempest-api-switchdev
        - networking-nuage-tempest-api-virtio-forwarder
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows
        - networking-nuage-tempest-scale
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/train/amphora-x64-haproxy.qcow2"
        - networking-nuage-tempest-virtio-vsdipam
        - networking-nuage-tempest-sriov-vsdipam
        - networking-nuage-tempest-baremetal-vsdipam
        - networking-nuage-tempest-scenario-vsdipam
        - networking-nuage-fwaas-v1:
            required-projects:
              - OpenStack/neutron-fwaas
            vars:
              devstack_plugins:
                neutron-fwaas: https://github.mv.usa.alcatel.com/OpenStack/neutron-fwaas.git
              devstack_localrc:
                USE_PYTHON3: true
                FORCE_CONFIG_DRIVE: true
        - tempest-full-vsdipam
        - ovs-restart

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      vsp_release: '20.5'
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest
