#!/bin/bash
#
# Nuage ml2 mechanism driver
# -----------------------------------------

# Save trace setting
NU_XTRACE=$(set +o | grep xtrace)
set +o xtrace

Q_ML2_PLUGIN_MECHANISM_DRIVERS=${Q_ML2_PLUGIN_MECHANISM_DRIVERS:-nuage}
Q_ML2_PLUGIN_TYPE_DRIVERS=${Q_ML2_PLUGIN_TYPE_DRIVERS:-vxlan}
Q_SERVICE_PLUGIN_CLASSES=${Q_SERVICE_PLUGIN_CLASSES:-NuagePortAttributes,NuageAPI,NuageNetTopology,trunk}
ML2_L3_PLUGIN=nuage_neutron.plugins.common.service_plugins.l3.NuageL3Plugin

function configure_neutron_nuage {
    echo "Configuring ML2 for Nuage"
    NUAGE_PLUGIN_CONF_DIR=$NEUTRON_CONF_DIR/plugins/nuage
    NUAGE_PLUGIN_CONF_FILE=$NUAGE_PLUGIN_CONF_DIR/nuage_plugin.ini

    mkdir -p $NUAGE_PLUGIN_CONF_DIR
    cp $DIR_NUAGE/etc/neutron/plugins/nuage/nuage_plugin.ini $NUAGE_PLUGIN_CONF_FILE

    iniset $NUAGE_PLUGIN_CONF_FILE restproxy base_uri $NUAGE_VSD_BASE_URI
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy serverssl $NUAGE_VSD_SERVER_SSL
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy serverauth $NUAGE_VSD_SERVER_AUTH
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy organization $NUAGE_VSD_ORGANIZATION
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy server $NUAGE_VSD_SERVERS
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy auth_resource $NUAGE_VSD_AUTH_RESOURCE
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy default_net_partition_name $NUAGE_VSD_DEF_NETPART_NAME
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy nuage_fip_underlay $NUAGE_FIP_UNDERLAY
    create_or_retrieve_cms cms_id
    iniset $NUAGE_PLUGIN_CONF_FILE restproxy cms_id $cms_id
    Q_PLUGIN_EXTRA_CONF_FILES=(${Q_PLUGIN_EXTRA_CONF_FILES[@]} $NUAGE_PLUGIN_CONF_FILE)

    iniset $NOVA_CONF neutron ovs_bridge $NOVA_OVS_BRIDGE

    _neutron_deploy_rootwrap_filters $DIR_NUAGE
}

# Restore xtrace
$NU_XTRACE

