#!/bin/bash
#
# Nuage Neutron Plugin
# ----------------------

# Save trace setting
NU_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function neutron_plugin_create_nova_conf {
    NOVA_OVS_BRIDGE=${NOVA_OVS_BRIDGE:-"br-int"}
    iniset $NOVA_CONF neutron ovs_bridge $NOVA_OVS_BRIDGE
    NOVA_VIF_DRIVER=${NOVA_VIF_DRIVER:-"nova.virt.libvirt.vif.LibvirtGenericVIFDriver"}
    LIBVIRT_FIREWALL_DRIVER=nova.virt.firewall.NoopFirewallDriver
    iniset $NOVA_CONF DEFAULT firewall_driver $LIBVIRT_FIREWALL_DRIVER
}

function neutron_plugin_install_agent_packages {
    :
}

function neutron_plugin_configure_common {
    Q_PLUGIN_CONF_PATH=etc/neutron/plugins/nuage
    Q_PLUGIN_CONF_FILENAME=nuage_plugin.ini
    Q_PLUGIN_CLASS="nuage_neutron.plugins.nuage.plugin.NuagePlugin"

    #Nuage specific Neutron defaults. Actual value must be set and sourced
    NUAGE_VSD_SERVERS=${NUAGE_VSD_SERVERS:-'localhost:8443'}
    NUAGE_VSD_SERVER_AUTH=${NUAGE_VSD_SERVER_AUTH:-'username:password'}
    NUAGE_VSD_ORGANIZATION=${NUAGE_VSD_ORGANIZATION:-'org'}
    NUAGE_VSD_SERVER_SSL=${NUAGE_VSD_SERVER_SSL:-'True'}
    NUAGE_VSD_BASE_URI=${NUAGE_VSD_BASE_URI:-'/'}
    NUAGE_VSD_AUTH_RESOURCE=${NUAGE_VSD_AUTH_RESOURCE:-'/'}
    NUAGE_VSD_DEF_NETPART_NAME=${NUAGE_VSD_DEF_NETPART_NAME:-''}
    NUAGE_VSD_CMS_ID=${NUAGE_VSD_CMS_ID:-''}
}

function neutron_plugin_configure_debug_command {
    :
}

function neutron_plugin_configure_dhcp_agent {
    :
}

function neutron_plugin_configure_l3_agent {
    :
}

function neutron_plugin_configure_plugin_agent {
    :
}

function has_neutron_plugin_security_group {
    # 1 means False here
    return 1
}

function neutron_plugin_configure_service {
    iniset $NEUTRON_CONF DEFAULT core_plugin $Q_PLUGIN_CLASS
    iniset /$Q_PLUGIN_CONF_FILE restproxy base_uri $NUAGE_VSD_BASE_URI
    iniset /$Q_PLUGIN_CONF_FILE restproxy serverssl $NUAGE_VSD_SERVER_SSL
    iniset /$Q_PLUGIN_CONF_FILE restproxy serverauth $NUAGE_VSD_SERVER_AUTH
    iniset /$Q_PLUGIN_CONF_FILE restproxy organization $NUAGE_VSD_ORGANIZATION
    iniset /$Q_PLUGIN_CONF_FILE restproxy server $NUAGE_VSD_SERVERS
    iniset /$Q_PLUGIN_CONF_FILE restproxy auth_resource $NUAGE_VSD_AUTH_RESOURCE
    iniset /$Q_PLUGIN_CONF_FILE restproxy default_net_partition_name $NUAGE_VSD_DEF_NETPART_NAME
}

function configure_neutron_nuage {
    create_or_retrieve_cms cms_id
    iniset /$Q_PLUGIN_CONF_FILE restproxy cms_id $cms_id
}

# Restore xtrace
$NU_XTRACE
