#!/bin/bash

# Nuage's nuagenetlib
# -------

# This file implements functions required to install and configure nuagenetlib


# Nuagenetlib devstack destination dir
NUAGENETLIB_DIR=${NUAGENETLIB_DIR:-$DEST/nuagenetlib}

# nuagenetlib repo
NUAGENETLIB_REPO=${NUAGENETLIB_REPO:-''}
NUAGENETLIB_BRANCH=${NUAGENETLIB_BRANCH:-master}

# Save trace setting
NUAGE_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_nuagenetlib {
    :
}

function init_nuagenetlib {
    :
}

function install_nuagenetlib {
    if [ -z "${NUAGENETLIB_REPO}" ]; then
        die $LINENO "Error - NUAGENETLIB_REPO required"
    fi
    git_clone $NUAGENETLIB_REPO $NUAGENETLIB_DIR $NUAGENETLIB_BRANCH
    cd $NUAGENETLIB_DIR
    sudo python setup.py develop
    export PYTHONPATH=$NUAGENETLIB_DIR/src:$PYTHONPATH
    cd -
}

function start_nuagenetlib {
    :
}

function stop_nuagenetlib {
    :
}

function check_nuagenetlib {
    :
}

# Restore xtrace
$NUAGE_XTRACE
