#!/bin/bash

# Copyright 2015 Alcatel-Lucent USA Inc.
#
# All Rights Reserved
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

NUAGE_OPENSTACK_NEUTRON_DIR=${NUAGE_OPENSTACK_NEUTRON_DIR:=$DEST/nuage-openstack-neutron}

Q_PLUGIN=${Q_PLUGIN:-$NEUTRON_CORE_PLUGIN}

# lib/neutron vs lib/neutron-legacy compat
Q_META_DATA_IP=${Q_META_DATA_IP:-$SERVICE_HOST}

Q_L3_ENABLED=True

# integration bridge
OVS_BRIDGE=${OVS_BRIDGE:-"alubr0"}

# IPAM driver
NUAGE_IPAM_DRIVER=${NUAGE_IPAM_DRIVER:-'nuage_internal'}

# Nuage VSP related settings
NUAGE_VSC_SERVER=${NUAGE_VSC_SERVER:-''}
NUAGE_VSD_SERVERS=${NUAGE_VSD_SERVERS:-'vsd.example.com:8443'}
NUAGE_VSD_SERVER_AUTH=${NUAGE_VSD_SERVER_AUTH:-'csproot:csproot'}
NUAGE_VSD_ORGANIZATION=${NUAGE_VSD_ORGANIZATION:-'csp'}
NUAGE_VSD_SERVER_SSL=${NUAGE_VSD_SERVER_SSL:-'True'}
NUAGE_VSD_BASE_URI=${NUAGE_VSD_BASE_URI:-'/nuage/api/v5_0'}
NUAGE_VSD_AUTH_RESOURCE=${NUAGE_VSD_AUTH_RESOURCE:-'/me'}
NUAGE_VSD_DEF_NETPART_NAME=${NUAGE_VSD_DEF_NETPART_NAME:-'OpenStackDefaultNetPartition'}
NUAGE_VSD_CMS_ID=${NUAGE_VSD_CMS_ID:-''}
NUAGE_VSD_CMS_NAME=${NUAGE_VSD_CMS_NAME:-''}

# Nuage FIP/PAT to underlay
NUAGE_FIP_UNDERLAY=${NUAGE_FIP_UNDERLAY:-'False'}
NUAGE_PAT=${NUAGE_PAT:-'legacy_disabled'}
NUAGE_UNDERLAY_DEFAULT=${NUAGE_UNDERLAY_DEFAULT:-'off'}

# Nuage metadata service
NUAGE_USE_METADATA=${NUAGE_USE_METADATA:-False}
NUAGE_NOVA_METADATA_URL=${NUAGE_NOVA_METADATA_URL:-http://${Q_META_DATA_IP}:8775}
NUAGE_METADATA_SHARED_SECRET=${NUAGE_METADATA_SHARED_SECRET:-}

# create the fake uplink for FIPtoUL
NUAGE_CREATE_FAKE_UPLINK=${NUAGE_CREATE_FAKE_UPLINK:-$NUAGE_FIP_UNDERLAY}
UPLINK_PREFIX_LEN=${UPLINK_PREFIX_LEN:-"24"}

# experimental features
NUAGE_EXPERIMENTAL_FEATURES=${NUAGE_EXPERIMENTAL_FEATURES:-''}

# Use IPv4
IP_VERSION=4

# Tempest options
IPV6_ENABLED='True'
IPV6_SUBNET_ATTRIBUTES_ENABLED='True'

# Nuage ml2 mechanism driver extensions
Q_ML2_PLUGIN_EXT_DRIVERS=${Q_ML2_PLUGIN_EXT_DRIVERS:-nuage_subnet,nuage_port,port_security}

if is_service_enabled q-fwaas neutron-fwaas-v1; then
    NETWORK_API_EXTENSIONS+=,fwaas,fwaasrouterinsertion
fi
if is_service_enabled q-qos neutron-qos; then
    NETWORK_API_EXTENSIONS+=,qos
fi
if is_service_enabled q-lbaasv2 neutron-lbaasv2; then
    NETWORK_API_EXTENSIONS+=,lbaasv2
fi

