#!/bin/bash

# Copyright 2015 Alcatel-Lucent USA Inc.
#
# All Rights Reserved
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

enable_service nuagenetlib

# Enable L3 for core plugin
if [ "${Q_PLUGIN}" == "nuage" ]; then
    Q_L3_ENABLED=True
fi

# Use IPv4
IP_VERSION=4

# Tempest options
IPV6_ENABLED=${IPV6_ENABLED:-'False'}
IPV6_SUBNET_ATTRIBUTES_ENABLED=${IPV6_SUBNET_ATTRIBUTES_ENABLED:-'False'}

