#!/bin/bash

# Copyright 2015 Alcatel-Lucent USA Inc.
#
# All Rights Reserved
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Nuage VSP related settings
NUAGE_VSD_SERVERS=${NUAGE_VSD_SERVERS:-'vsd.example.com:8443'}
NUAGE_VSD_SERVER_AUTH=${NUAGE_VSD_SERVER_AUTH:-'csproot:csproot'}
NUAGE_VSD_ORGANIZATION=${NUAGE_VSD_ORGANIZATION:-'csp'}
NUAGE_VSD_SERVER_SSL=${NUAGE_VSD_SERVER_SSL:-'True'}
NUAGE_VSD_BASE_URI=${NUAGE_VSD_BASE_URI:-'/nuage/api/v5_0'}
NUAGE_VSD_AUTH_RESOURCE=${NUAGE_VSD_AUTH_RESOURCE:-'/me'}
NUAGE_VSD_DEF_NETPART_NAME=${NUAGE_VSD_DEF_NETPART_NAME:-'OpenStackDefaultNetPartition'}
NUAGE_VSD_CMS_ID=${NUAGE_VSD_CMS_ID:-''}
NUAGE_VSD_CMS_NAME=${NUAGE_VSD_CMS_NAME:-''}

# Nuage FIP to underlay
NUAGE_FIP_UNDERLAY=${NUAGE_FIP_UNDERLAY:-'False'}

# integration bridge
OVS_BRIDGE=${OVS_BRIDGE:-"alubr0"}

# Enable L3 for core plugin
if [ "${Q_PLUGIN}" == "nuage" ]; then
    Q_L3_ENABLED=True
fi

# Use IPv4
IP_VERSION=4

# Tempest options
IPV6_ENABLED='True'
IPV6_SUBNET_ATTRIBUTES_ENABLED='True'

# Nuage ml2 mechanism driver extensions
Q_ML2_PLUGIN_EXT_DRIVERS=${Q_ML2_PLUGIN_EXT_DRIVERS:-nuage_subnet,nuage_port,port_security}

# TODO(gridinv): bug work around
# https://bugs.launchpad.net/devstack/+bug/1698129
# once it's fixed. remove this.
AGENT_BINARY="/bin/false"

