- hosts: controller
  tasks:
    - name: fetch vsp_info
      slurp:
        src: /etc/ci/vsp_info.yaml
      register: vsp_info

- hosts: all
  vars:
    vsp: "{{ hostvars['controller']['vsp_info']['content'] | b64decode | from_yaml}}"
    devstack_localrc:
      NUAGE_VSD_SERVERS: "{{ vsp['vsd_server'] }}"
      NUAGE_VSC_SERVER: "{{ vsp['vsc_controller'] }}"
      NUAGE_VSP_RELEASE: "{{ vsp['nuage_vsp_release'] }}"
  roles:
    - setup-nuage-source-dirs
    - write-vsp-devstack-local-conf
